# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(first_name: "Jim", last_name: "Doe", email: "jimdoe@gmail.com", password: "password")
User.create(first_name: "Grace", last_name: "Jones", email: "gracejones@gamil.com", password: "password")
User.create(first_name: "John", last_name: "Smith", email: "john.smith@gmail.com", password: "password")
User.create(first_name: "Luke", last_name: "Brown", email: "luke.brown23@gmail.com", password: "password")
User.create(first_name: "Danni", last_name: "Wong", email: "danwong@gmail.com", password: "password")
User.create(first_name: "Sarah", last_name: "Lee", email: "sarah.lee@hotmail.com", password: "password")
User.create(first_name: "John", last_name: "Snow", email: "kingofthenorth@got.com", password: "password")
User.create(first_name: "Luke", last_name: "Skywalker", email: "iamyourfather@gmail.com", password: "password")
User.create(first_name: "Anya", last_name: "Marie", email: "ani.marie@gmail.com", password: "password")
User.create(first_name: "Leah", last_name: "Thompson", email: "leahthompson@gmail.com", password: "password")
User.create(first_name: "Carrie", last_name: "Young", email: "c.young@yahoo.com", password: "password")
User.create(first_name: "Garrett", last_name: "Olson", email: "big-o@gmail.com", password: "password")
User.create(first_name: "Henry", last_name: "Han", email: "iloveirene@gmail.com", password: "password")
User.create(first_name: "Nyki", last_name: "Nyki", email: "artist@art.com", password: "password")
User.create(first_name: "Vanessa", last_name: "Kim", email: "v.kim@gmail.com", password: "password")
User.create(first_name: "Michelle", last_name: "Kim", email: "myadvisor@gmail.com", password: "password")
User.create(first_name: "Walker", last_name: "Sam", email: "idk@gmail.com", password: "password")
User.create(first_name: "Mike", last_name: "Michaelson", email: "mermike@gmail.com", password: "password")
User.create(first_name: "Joe", last_name: "Bumba", email: "amazingvoice@gmail.com", password: "password")
User.create(first_name: "Lucas", last_name: "Compton", email: "tallguy@gmail.com", password: "password")
User.create(first_name: "Dylan", last_name: "Jones", email: "dj@gmail.com", password: "password")
User.create(first_name: "Robel", last_name: "Berhani", email: "afroguy@gmail.com", password: "password")
User.create(first_name: "Fred", last_name: "Smith", email: "cravatastic@mysterygang.com", password: "password")
User.create(first_name: "Velma", last_name: "Ng", email: "glassesgirl@mysterygang.com", password: "password")
User.create(first_name: "Shaggy", last_name: "Woods", email: "skoooobs@mysterygang.com", password: "password")
User.create(first_name: "Dave", last_name: "Flutsis", email: "software@yahoo.com", password: "password")
User.create(first_name: "Nick", last_name: "Johnson", email: "bestboy@gmail.com", password: "password")
User.create(first_name: "Christy", last_name: "Fukushima", email: "haikyuu@watching.com", password: "password")
User.create(first_name: "Larry", last_name: "Dancer", email: "teaching.dance@gmail.com", password: "password")
User.create(first_name: "Simon", last_name: "Clinton", email: "simonclinton@gmail.com", password: "password")
User.create(first_name: "Eli", last_name: "Appel", email: "eli.friend@gmail.com", password: "password")
User.create(first_name: "Forrest", last_name: "Nolan", email: "nolan.f@gmail.com", password: "password")
User.create(first_name: "Sadie", last_name: "Alan", email: "myqueen@gmail.com", password: "password")
User.create(first_name: "Marika", last_name: "Stuurman", email: "anotherqueen@gmail.com", password: "password")
User.create(first_name: "Maya", last_name: "Hirota", email: "sister@gmail.com", password: "password")
User.create(first_name: "Carly", last_name: "Tarricone", email: "cutiepie97@hotmail.com", password: "password")
User.create(first_name: "Marly", last_name: "Medina", email: "mmla@gmail.com", password: "password")
User.create(first_name: "Jordan", last_name: "Vincent", email: "jordanvincent@yahoo.com", password: "password")
User.create(first_name: "Johanna", last_name: "Leonhardt", email: "kobegirl@gmail.com", password: "password")
User.create(first_name: "Scott", last_name: "David", email: "s.david@gmail.com", password: "password")
