# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'open-uri'


User.destroy_all
Spot.destroy_all

user1 = User.create(first_name: "Jim", last_name: "Doe", email: "jimdoe@gmail.com", password: "password")
user2 = User.create(first_name: "Grace", last_name: "Jones", email: "gracejones@gamil.com", password: "password")
user3 = User.create(first_name: "John", last_name: "Smith", email: "john.smith@gmail.com", password: "password")
user4 = User.create(first_name: "Luke", last_name: "Brown", email: "luke.brown23@gmail.com", password: "password")
user5 = User.create(first_name: "Danni", last_name: "Wong", email: "danwong@gmail.com", password: "password")
user6 = User.create(first_name: "Sarah", last_name: "Lee", email: "sarah.lee@hotmail.com", password: "password")
user7 = User.create(first_name: "John", last_name: "Snow", email: "kingofthenorth@got.com", password: "password")
user8 = User.create(first_name: "Luke", last_name: "Jennings", email: "iamyourfather@gmail.com", password: "password")
user9 = User.create(first_name: "Anya", last_name: "Marie", email: "ani.marie@gmail.com", password: "password")
user10 = User.create(first_name: "Leah", last_name: "Thompson", email: "leahthompson@gmail.com", password: "password")
user11 = User.create(first_name: "Carrie", last_name: "Young", email: "c.young@yahoo.com", password: "password")
user12 = User.create(first_name: "Garrett", last_name: "Olson", email: "big-o@gmail.com", password: "password")
user13 = User.create(first_name: "Henry", last_name: "Han", email: "iloveirene@gmail.com", password: "password")
user14 = User.create(first_name: "Nyki", last_name: "Wiehe", email: "artist@art.com", password: "password")
user15 = User.create(first_name: "Vanessa", last_name: "Kim", email: "v.kim@gmail.com", password: "password")
user16 = User.create(first_name: "Michelle", last_name: "Kim", email: "myadvisor@gmail.com", password: "password")
user17 = User.create(first_name: "Walker", last_name: "Sam", email: "idk@gmail.com", password: "password")
user18 = User.create(first_name: "Mike", last_name: "Michaelson", email: "mermike@gmail.com", password: "password")
user19 = User.create(first_name: "Joe", last_name: "Bumba", email: "amazingvoice@gmail.com", password: "password")
user20 = User.create(first_name: "Lucas", last_name: "Compton", email: "tallguy@gmail.com", password: "password")
user21 = User.create(first_name: "Dylan", last_name: "Jones", email: "dj@gmail.com", password: "password")
user22 = User.create(first_name: "Robel", last_name: "Berhani", email: "afroguy@gmail.com", password: "password")
user23 = User.create(first_name: "Fred", last_name: "Smith", email: "cravatastic@mysterygang.com", password: "password")
user24 = User.create(first_name: "Lacey", last_name: "Ng", email: "glassesgirl@mysterygang.com", password: "password")
user25 = User.create(first_name: "Phil", last_name: "Woods", email: "skoooobs@mysterygang.com", password: "password")
user26 = User.create(first_name: "Dave", last_name: "Flutsis", email: "software@yahoo.com", password: "password")
user27 = User.create(first_name: "Nick", last_name: "Johnson", email: "bestboy@gmail.com", password: "password")
user28 = User.create(first_name: "Christy", last_name: "Fukushima", email: "haikyuu@watching.com", password: "password")
user29 = User.create(first_name: "Jake", last_name: "Wood", email: "teaching.dance@gmail.com", password: "password")
user30 = User.create(first_name: "Simon", last_name: "Clinton", email: "simonclinton@gmail.com", password: "password")
user31 = User.create(first_name: "Eli", last_name: "Appel", email: "eli.friend@gmail.com", password: "password")
user32 = User.create(first_name: "Forrest", last_name: "Nolan", email: "nolan.f@gmail.com", password: "password")
user33 = User.create(first_name: "Sadie", last_name: "Alan", email: "myqueen@gmail.com", password: "password")
user34 = User.create(first_name: "Marika", last_name: "Stuurman", email: "anotherqueen@gmail.com", password: "password")
user35 = User.create(first_name: "Maya", last_name: "Hirota", email: "sister@gmail.com", password: "password")
user36 = User.create(first_name: "Carly", last_name: "Tarricone", email: "cutiepie97@hotmail.com", password: "password")
user37 = User.create(first_name: "Marly", last_name: "Medina", email: "mmla@gmail.com", password: "password")
user38 = User.create(first_name: "Jordan", last_name: "Vincent", email: "jordanvincent@yahoo.com", password: "password")
user39 = User.create(first_name: "Johanna", last_name: "Leonhardt", email: "kobegirl@gmail.com", password: "password")
user40 = User.create(first_name: "Scott", last_name: "David", email: "s.david@gmail.com", password: "password")


spot1 = Spot.create(name: "Ocean Cliffs Campground", host_id: user2.id, description: "Located along the majestic California coast, Ocean Cliffs Campground offers camping with the emphasis on Family. Enjoy tent camping on meadowed floor as you watch the kids play on the adjacent beach. Enjoy campfire lit nights that will create lasting memories. ", lat: 36.242849, lng: -121.818619, park: "Big Sur", spot_type: "camping", price_per_night: 30.00, minimum_nights: 1, nearby_attractions: "Bixby Creek Bridge, Julia Pfeiffer Burns State Park, Big Sur River", bring_your_own_tents: true, sites: 4, guests_per_site: 4, park_at_listing: true, ada_access: false, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, slideouts: false, biking: true, hiking: true, boating: true, fishing: true, paddling: true, swimming: true, snow_sports: false, wildlife_watching: false, climbing: false, horseback_riding: false, off_roading: false, mountainous: false, desert: false, forest: false, coastal: true, weather: "Temperate", elevation: "135ft", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Go straight to camp", booking_acceptance: "6 months out")
spot2 = Spot.create(name: "Big Sur Airstream", host_id: user3.id, description: "CAMP IN A MODERN AIRSTREAM TRAILER: Get away for the weekend by staying in our cute Airstream located by the beach in Big Sur. It provides all the essentials from a kitchenette to working shower. For more details, see below or email host.", lat: 36.224317, lng: -121.763058, park: "Big Sur", spot_type: "glamping", slideouts: false, price_per_night: 120.00, minimum_nights: 2, nearby_attractions: "Bixby Creek Bridge, Julia Pfeiffer Burns State Park, Big Sur River", bring_your_own_tents: false, sites: 1, guests_per_site: 2, park_at_listing: true, ada_access: false, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: true, showers: true, wifi: true, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, lodging_type: "Airstream", biking: true, hiking: true, boating: false, fishing: false, paddling: true, swimming: true, snow_sports: false, wildlife_watching: false, climbing: false, horseback_riding: false, off_roading: false, mountainous: false, desert: false, forest: false, coastal: true, weather: "Temperate", elevation: "135ft", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Meet with host", booking_acceptance: "6 months out")
spot3 = Spot.create(name: "Sunset Fields Campground", host_id: user4.id, description: "Sunset Fields Camground is a barebones site full of natural beauty of the desert. During the summer the weather is extremely hot. Please come prepared with all the essentials you require.", lat: 36.940509, lng: -117.378268, park: "Death Valley National Park", spot_type: "camping", price_per_night: 25.00, minimum_nights: 1, nearby_attractions: "Death Valley National Park", bring_your_own_tents: true, sites: 5, guests_per_site: 4, park_at_listing: true, ada_access: false, toilet_available: true, pets_allowed: false, campfires: false, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, slideouts: false, biking: false, hiking: true, boating: false, fishing: false, paddling: false, swimming: false, snow_sports: false, wildlife_watching: false, climbing: false, horseback_riding: false, off_roading: false, mountainous: false, desert: true, forest: false, coastal: false, weather: "Hot", elevation: "-282.2ft", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Moderate", on_arrival: "Go straight to camp", booking_acceptance: "4 months out")
spot4 = Spot.create!(name: "Desert Yurt", host_id: user5.id, description: "Enjoy the experience of sleeping in a Yurt in the peaceful desert landscape of Death Valley. It's quiet here; you don't hear traffic noise or sirens, and there are no street lights, so at night you can see the stars. The usual noises heard are coyotes howling in the evenings", lat: 36.771275, lng: -117.743972, park: "Death Valley National Park", spot_type: "glamping", slideouts: false, price_per_night: 200.00, minimum_nights: 2, nearby_attractions: "Death Valley National Park", bring_your_own_tents: false, sites: 1, guests_per_site: 5, park_at_listing: false, ada_access: true, toilet_available: true, pets_allowed: true, campfires: false, picnic_table_available: true, potable_water: true, kitchen: true, showers: true, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, lodging_type: "Yurt", biking: false, hiking: true, boating: false, fishing: false, paddling: false, swimming: false, snow_sports: false, wildlife_watching: true, climbing: false, horseback_riding: false, off_roading: false, mountainous: false, desert: true, forest: false, coastal: false, weather: "Hot", elevation: "-282.2ft", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Meet with host", booking_acceptance: "8 months out")
spot5 = Spot.create(name: "Joshua's Bush Campground", host_id: user6.id, description: "Joshua's Bush Campground is like a home without walls, offering panoramic desert views that will take your breath away. Joshua's Bush is surrounded with open space and situated next to BLM land. There are endless outdoor recreational opportunities, including hiking, biking, bouldering, breathtaking sunrises and sunsets, dark starry nights, and quiet solitude. The village of Joshua Tree is only a few miles down the road and offers unique options for dining and shopping. Most of our businesses are independent, locally owned and charged by the positive forces of Joshua Tree ;-)", lat: 33.979878, lng: -116.003761, park: "Joshua Tree National Park", spot_type: "camping", price_per_night: 30.00, minimum_nights: 1, nearby_attractions: "Joshua Tree National Park, Skull Rock", bring_your_own_tents: true, sites: 3, guests_per_site: 5, park_at_listing: true, ada_access: false, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, slideouts: false, biking: true, hiking: true, boating: false, fishing: false, paddling: false, swimming: false, snow_sports: false, wildlife_watching: false, climbing: true, horseback_riding: false, off_roading: false, mountainous: false, desert: true, forest: false, coastal: false, weather: "Hot", elevation: "2,736ft", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Moderate", on_arrival: "Go straight to camp", booking_acceptance: "6 months out")
spot6 = Spot.create(name: "Blue House by the Springs", host_id: user7.id, description: "Perfect for groups looking to get away! Comfortable and bright with great views of San Jacinto in Morongo Valley California Includes Air Conditioning, coffee, fridge and microwave. The Blue House is perfect for those looking for a more isolated getaway. And the stars at night are incredible!  We are centrally located between Palm Springs & Joshua Tree National Park and minutes away from Palm Springs Aerial Tramway, Pappy and Harriett’s, Pioneertown, the Integritron, Joshua Tree and all of the music/art festivals.", lat: 33.922046, lng: -116.377428, park: "Joshua Tree National Park", spot_type: "glamping", slideouts: false, price_per_night: 275.00, minimum_nights: 2, nearby_attractions: "Joshua Tree National Park, Skull Rock, Palm Springs", bring_your_own_tents: false, sites: 1, guests_per_site: 5, park_at_listing: true, ada_access: true, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: false, potable_water: true, kitchen: true, showers: true, wifi: true, bins_available: true, laundry: true, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, lodging_type: "House", biking: true, hiking: true, boating: false, fishing: false, paddling: false, swimming: false, snow_sports: false, wildlife_watching: false, climbing: false, horseback_riding: false, off_roading: false, mountainous: false, desert: true, forest: false, coastal: false, weather: "Hot", elevation: "2,736ft", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Enter house via guest code", booking_acceptance: "8 months out")
spot7 = Spot.create(name: "Sky Tipis", host_id: user8.id, description: 'Enjoy the peace and quiet of the outdoors in our beautifully decorated tipis.  These canvas wall tipis offer a unique "glamping" experience at Sky Tipis.  Built on sturdy platforms with ample room, these tents boast 22" high queen size airbeds with luxurious bedding and plenty of room for you to relax and unwind.', lat: 33.994735, lng: -115.953317, park: "Joshua Tree National Park", spot_type: "glamping", slideouts: false, price_per_night: 85.00, minimum_nights: 1, nearby_attractions: "Joshua Tree National Park, Skull Rock", bring_your_own_tents: false, sites: 3, guests_per_site: 2, park_at_listing: true, ada_access: false, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, lodging_type: "Tipi", biking: true, hiking: true, boating: false, fishing: false, paddling: false, swimming: false, snow_sports: false, wildlife_watching: true, climbing: true, horseback_riding: false, off_roading: true, mountainous: false, desert: true, forest: false, coastal: false, weather: "Hot", elevation: "2,736ft", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Moderate", on_arrival: "Meet with host", booking_acceptance: "6 months out")
spot8 = Spot.create(name: "Philips Camp", host_id: user9.id, description: "It is warm during summer months it’s usually nice in the evenings.", lat: 36.784993, lng: -118.654978, park: "Kings Canyon National Park", spot_type: "camping", price_per_night: 30.00, minimum_nights: 1, nearby_attractions: "Kings Canyon National Park", bring_your_own_tents: true, sites: 4, guests_per_site: 4, park_at_listing: true, ada_access: false, toilet_available: false, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, slideouts: false, biking: true, hiking: true, boating: false, fishing: false, paddling: false, swimming: false, snow_sports: false, wildlife_watching: true, climbing: true, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate", elevation: "4,000ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Flexible", on_arrival: "Go straight to camp", booking_acceptance: "6 months out")
spot9 = Spot.create(name: "Shady Meadow Lot", host_id: user10.id, description: "Mellow community vibes, stargazing, Saturday bonfire nights, and more for wilderness and bug-loving mountain going adventure seekers keen to discover Kings Canyon. I M P O R T A N T : Please let us know the TYPE & LENGTH of your RV/trailer/van when requesting the booking (your request will be declined without that info) Disclaimer: Warm greetings to you from our piece of paradise! This is a new reality we are all getting used to, please be kind and mindful while at the camp and adventuring in the area, respecting other’s space and maintaining the safe six-foot distance. We are unsure what official COVID-19 guidelines may be at the time of your visit but we will just mirror them. Things have, and still may change daily. Please be flexible, we truly appreciate your patience and understanding.", lat: 36.795873, lng: -118.685501, park: "Kings Canyon National Park", spot_type: "RV", price_per_night: 28.00, minimum_nights: 1, nearby_attractions: "Kings Canyon National Park", bring_your_own_tents: false, sites: 8, guests_per_site: 4, park_at_listing: true, ada_access: true, toilet_available: false, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: true, surface_type: "Meadow", max_length: "24ft", surface_levelness: "Flat", slideouts: false, biking: true, hiking: true, boating: false, fishing: false, paddling: false, swimming: false, snow_sports: false, wildlife_watching: true, climbing: true, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate-Hot", elevation: "4,000ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Moderate", on_arrival: "Park in booked spot", booking_acceptance: "4 months out")
spot10 = Spot.create(name: "Tent Heaven", host_id: user11.id, description: "Pitch your tent in our forest! Located right outside of Lassen National Park, our campground is secluded yet easily accessible. The creek is great for fishing and being so close to the National Park and surrounded by National Forest, the hiking opportunities are endless!", lat: 40.575097, lng: -120.713288, park: "Lassen Volcanic National Park", spot_type: "camping", price_per_night: 30.00, minimum_nights: 1, nearby_attractions: "Lassen Volcanic National Park", bring_your_own_tents: true, sites: 6, guests_per_site: 4, park_at_listing: true, ada_access: true, toilet_available: true, pets_allowed: false, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, slideouts: false, biking: true, hiking: true, boating: false, fishing: true, paddling: false, swimming: false, snow_sports: false, wildlife_watching: true, climbing: false, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: false, coastal: false, weather: "Temperate", elevation: "8500ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Go straight to camp", booking_acceptance: "9 months out")
spot11 = Spot.create(name: "Mermike Memorial Campground", host_id: user12.id, description: "We have a number of primitive camping spots. The spots are spread out to insure privacy and is surrounded by the forest and is loaded with deer, squirrels, turkeys and other forest animals.", lat: 40.606854, lng: -121.461832, park: "Lassen Volcanic National Park", spot_type: "camping", price_per_night: 28.00, minimum_nights: 1, nearby_attractions: "Lassen Volcanic National Park", bring_your_own_tents: true, sites: 5, guests_per_site: 6, park_at_listing: true, ada_access: false, toilet_available: false, pets_allowed: true, campfires: true, picnic_table_available: false, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: false, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, slideouts: false, biking: true, hiking: true, boating: true, fishing: true, paddling: false, swimming: false, snow_sports: false, wildlife_watching: true, climbing: false, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate-Cool", elevation: "8500ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Moderate", on_arrival: "Go straight to camp", booking_acceptance: "6 months out")
spot12 = Spot.create(name: "Winter Tiny House", host_id: user13.id, description: "Cute winter escape hidden away in Lassen. While we recommend the property for cozy winter getaways, the tiny house is also great for summer trips as well. Inside, guests can enjoy 2 single beds, basic cooking essentials, and coffee station", lat: 40.470401, lng: -121.329986, park: "Lassen Volcanic National Park", spot_type: "glamping", slideouts: false, price_per_night: 75.00, minimum_nights: 1, nearby_attractions: "Lassen Volcanic National Park", bring_your_own_tents: false, sites: 1, guests_per_site: 2, park_at_listing: false, ada_access: false, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, lodging_type: "tiny house", biking: false, hiking: true, boating: false, fishing: false, paddling: false, swimming: false, snow_sports: true, wildlife_watching: true, climbing: true, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Cold", elevation: "8500ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Retrieve key from lockbox", booking_acceptance: "12 months out")
spot13 = Spot.create(name: "Forest Floor RV Park", host_id: user14.id, description: "Mellow community vibes, stargazing, Saturday bonfire nights, and more for wilderness and bug-loving mountain going adventure seekers keen to discover Lassen Volcanic National Park. I M P O R T A N T : Please let us know the TYPE & LENGTH of your RV/trailer/van when requesting the booking (your request will be declined without that info) Disclaimer: Warm greetings to you from our piece of paradise! This is a new reality we are all getting used to, please be kind and mindful while at the camp and adventuring in the area, respecting other’s space and maintaining the safe six-foot distance. We are unsure what official COVID-19 guidelines may be at the time of your visit but we will just mirror them. Things have, and still may change daily. Please be flexible, we truly appreciate your patience and understanding.", lat: 40.455265, lng: -121.530825, park: "Lassen Volcanic National Park", spot_type: "RV", price_per_night: 35.00, minimum_nights: 1, nearby_attractions: "Lassen Volcanic National Park", bring_your_own_tents: false, sites: 16, guests_per_site: 4, park_at_listing: true, ada_access: true, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: true, water_hookup: true, generator_allowed: false, sewage_hookup: true, tv_hookup: false, pull_in_site: true, surface_type: "Paved or gravel", max_length: "24ft", surface_levelness: "Flat", slideouts: false, biking: true, hiking: true, boating: false, fishing: false, paddling: false, swimming: false, snow_sports: false, wildlife_watching: true, climbing: false, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate-Hot", elevation: "8500ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Moderate", on_arrival: "Park in booked spot", booking_acceptance: "6 months out")
spot14 = Spot.create(name: "Camp Tahoe", host_id: user15.id, description: "So close yet so secluded. Camp is a short drive from Donner Summit and Donner Lake and Truckee. Located in the beautiful Tahoe National Forest on a large stretch of mountain evergreens and other native trees. There is plenty of space between sites. Some sites listed are rugged, there are also remote 4x4 access only sites not listed, message me for info. ", lat: 39.478512, lng: -120.525006, park: "Tahoe National Forest", spot_type: "camping", price_per_night: 28.00, minimum_nights: 1, nearby_attractions: "Tahoe National Forest, Lake Tahoe", bring_your_own_tents: true, sites: 12, guests_per_site: 4, park_at_listing: true, ada_access: true, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: false, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, slideouts: false, biking: true, hiking: true, boating: true, fishing: true, paddling: true, swimming: true, snow_sports: true, wildlife_watching: true, climbing: false, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate", elevation: "7500ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Moderate", on_arrival: "Go straight to camp", booking_acceptance: "6 months out")
spot15 = Spot.create(name: "Lakeview Campground", host_id: user16.id, description: "Located in a beatiful forested area along the perimeter of a lake, Lakeview Campground offers camping with the emphasis on Family. Enjoy tent camping on the forest floor as you watch the kids play in the lake. Enjoy campfire lit nights that will create lasting memories.", lat: 39.440279, lng: -120.647704, park: "Tahoe National Forest", spot_type: "camping", price_per_night: 32.00, minimum_nights: 1, nearby_attractions: "Tahoe National Forest, Lake Tahoe", bring_your_own_tents: true, sites: 4, guests_per_site: 5, park_at_listing: true, ada_access: false, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, slideouts: false, biking: true, hiking: true, boating: true, fishing: true, paddling: true, swimming: true, snow_sports: true, wildlife_watching: true, climbing: false, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate", elevation: "7500ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Go straight to camp", booking_acceptance: "8 months out")
spot16 = Spot.create(name: "Cabin in the Woods", host_id: user17.id, description: "This is our top-end accommodation a 2 bedroom cabin with its own kitchen, bathroom and living room with a woodstove. A beautiful spot to check out. Its rustic look and modern comfort esures that this cabin is the perfect getaway for any city-dwellers looking for a quiet escape.", lat: 39.347448, lng: -120.290386, park: "Tahoe National Forest", spot_type: "glamping", slideouts: false, price_per_night: 250.00, minimum_nights: 1, nearby_attractions: "Tahoe National Forest, Lake Tahoe", bring_your_own_tents: false, sites: 1, guests_per_site: 4, park_at_listing: true, ada_access: true, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: true, showers: true, wifi: true, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, lodging_type: "Cabin", biking: true, hiking: true, boating: true, fishing: true, paddling: true, swimming: true, snow_sports: true, wildlife_watching: true, climbing: true, horseback_riding: true, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate", elevation: "7500ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Meet with host", booking_acceptance: "6 months out")
spot17 = Spot.create(name: "Valley Vista Park", host_id: user18.id, description: "Bring your camper and spend afternoons watching beautiful sunsets and wildlife from our land. Spectacular expansive views across the valley to the Sierras. Conveniently 15 minutes from South Reno (40 minutes from North Lake Tahoe), the silence and absolute privacy here are restorative and replenishing.  We ask all guest to practice a “leave no trace” philosophy. Thanks for visiting and enjoy your time!  ", lat: 39.337183, lng: -120.703821, park: "Tahoe National Forest", spot_type: "RV", price_per_night: 25.00, minimum_nights: 1, nearby_attractions: "Tahoe National Forest, Lake Tahoe", bring_your_own_tents: true, sites: 5, guests_per_site: 4, park_at_listing: true, ada_access: true, toilet_available: true, pets_allowed: true, campfires: false, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: true, water_hookup: true, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: true, surface_type: "Paved or gravel", max_length: "20ft", surface_levelness: "Flat", slideouts: false, biking: true, hiking: true, boating: true, fishing: true, paddling: true, swimming: true, snow_sports: true, wildlife_watching: true, climbing: true, horseback_riding: true, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate", elevation: "7500ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Park in booked spot", booking_acceptance: "12 months out")
spot18 = Spot.create(name: "Lakeside RV Parking Lot", host_id: user19.id, description: "Park your vehicle on right on Lake Tahoe. The setting is a paved parking area, our koi pond and recycled stream with large pines surrounding it. Trails are right out the door and we are next to the national forest.", lat: 39.237378, lng: -120.064205, park: "Tahoe National Forest", spot_type: "RV", price_per_night: 35.00, minimum_nights: 1, nearby_attractions: "Tahoe National Forest, Lake Tahoe", bring_your_own_tents: false, sites: 10, guests_per_site: 4, park_at_listing: true, ada_access: true, toilet_available: false, pets_allowed: false, campfires: false, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, surface_type: "Paved", max_length: "24ft", surface_levelness: "Flat", slideouts: false, biking: true, hiking: false, boating: true, fishing: true, paddling: true, swimming: true, snow_sports: false, wildlife_watching: false, climbing: false, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate-Hot", elevation: "7500ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Park in booked spot", booking_acceptance: "8 months out")
spot19 = Spot.create(name: "Friendship Valley Campground", host_id: user20.id, description: "COVID-19 NOTE: While campsites are spaced far apart, there is only one bathroom, so please practice safe hand washing/sanitizing, and please practice physical distancing. You can pull your vehicle right up to this tent site. While this site does not have as much privacy as the other tent sites, you have the advantage of proximity to your car, shade from trees, and a picnic table in the shade of an old live oak. Note that Friendship Valley is on a very rough dirt road, which gets worse every year. A higher clearance vehicle is necessary and 4-wheel drive is ideal. Sedans often bottom out on this road and are not recommended. Please drive no faster than 5 mph when going past neighbors' homes. LATE SUMMER NOTE: During California's peak fire season, the electric utility company (PG&E) sometimes shuts off power to the area to prevent sparks from causing wildfires, especially when the weather is hot and windy. When PG&E shuts off power, the well pump will not run and there is no running water in camp. This only happens a few days a year. I will notify campers when PG&E notifies me, so that campers can bring water for drinking, hand washing and toilet flushing.", lat: 37.760328, lng: -119.485161, park: "Yosemite National Park", spot_type: "camping", price_per_night: 28.00, minimum_nights: 1, nearby_attractions: "Yosemite National Park", bring_your_own_tents: true, sites: 8, guests_per_site: 4, park_at_listing: true, ada_access: false, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: false, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, slideouts: false, biking: true, hiking: true, boating: false, fishing: true, paddling: false, swimming: false, snow_sports: false, wildlife_watching: true, climbing: true, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate", elevation: "4,000ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Moderate", on_arrival: "Go straight to camp", booking_acceptance: "7 months out")
spot20 = Spot.create(name: "Grassy Meadow Campground", host_id: user21.id, description: "Grassy Meadow Campground is the perfect place to enjoy the sunset and stargaze next to a campfire after an adventurous day in the Yosemite region. Yosemite tent camping without all the crowds and tour buses is what you can expect. Have a large group? Grassy Meadow Campground offers discounts for larger parties of up to 25 campers. Message us to reserve more than 5 sites!", lat: 37.728029, lng: -119.563756, park: "Yosemite National Park", spot_type: "camping", price_per_night: 35.00, minimum_nights: 1, nearby_attractions: "Yosemite National Park", bring_your_own_tents: true, sites: 15, guests_per_site: 5, park_at_listing: true, ada_access: true, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, slideouts: false, biking: false, hiking: true, boating: false, fishing: false, paddling: false, swimming: false, snow_sports: false, wildlife_watching: true, climbing: true, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate", elevation: "4,000ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Go straight to camp", booking_acceptance: "4 months out")
spot21 = Spot.create(name: "Yosemite Bungalow", host_id: user22.id, description: "Brand new cedar 1 room rustic cabin with queen bed. Beatiful blue pine pitched ceiling with recessed lighting...very homey! Electicity. Covered front porch with rocking chairs just waiting for you. Fire and bbq pits and picnic table at site. Horseahoe pit for your entertainment. Bring your own bedding or sleeping bags.", lat: 37.737081, lng: -119.595284, park: "Yosemite National Park", spot_type: "glamping", slideouts: false, price_per_night: 82.00, minimum_nights: 2, nearby_attractions: "Yosemite National Park", bring_your_own_tents: false, sites: 1, guests_per_site: 2, park_at_listing: true, ada_access: true, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, lodging_type: "Cabin", biking: true, hiking: true, boating: false, fishing: true, paddling: false, swimming: false, snow_sports: false, wildlife_watching: true, climbing: false, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate", elevation: "4,000ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Meet with host", booking_acceptance: "12 months out")
spot22 = Spot.create(name: "The Big Tents", host_id: user23.id, description: "Enjoy the peace and quiet of the outdoors in our beautifully decorated tent cabins. These 10x12 canvas wall tents offer a unique 'glamping' experience at The Big Tents. Built on sturdy platforms with ample room outside on the patio decks, these tents boast 22inch high queen size airbeds with luxurious bedding and plenty of room for you to relax and unwind. Perfect for two adults to escape the city and spend quality time surrounded by nature. Plenty of extra blankets and a small space heater and/or fan if needed. Two towels are provided. Electricity can be accessed from inside the tents to plug in your phone, tablet, etc. Lounge on the decks on cushioned lounge chairs or relax at a nearby seating area exclusively situated between the three tents. Please be flexible, we truly appreciate your patience and understanding.", lat: 37.744001, lng: -119.568380, park: "Yosemite National Park", spot_type: "glamping", slideouts: false, price_per_night: 70.00, minimum_nights: 1, nearby_attractions: "Yosemite National Park", bring_your_own_tents: false, sites: 3, guests_per_site: 2, park_at_listing: true, ada_access: true, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: false, water_hookup: false, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: false, lodging_type: "Tent cabin", biking: true, hiking: true, boating: false, fishing: true, paddling: false, swimming: false, snow_sports: false, wildlife_watching: true, climbing: false, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate", elevation: "4,000ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Moderate", on_arrival: "Meet with host", booking_acceptance: "8 months out")
spot23 = Spot.create(name: "Handy's RV Park", host_id: user19.id, description: "Mellow community vibes, stargazing, Saturday bonfire nights, and more for wilderness and bug-loving mountain going adventure seekers keen to discover Yosemite. I M P O R T A N T : Please let us know the TYPE & LENGTH of your RV/trailer/van when requesting the booking (your request will be declined without that info) Disclaimer: Warm greetings to you from our piece of paradise! This is a new reality we are all getting used to, please be kind and mindful while at the camp and adventuring in the area, respecting other’s space and maintaining the safe six-foot distance. We are unsure what official COVID-19 guidelines may be at the time of your visit but we will just mirror them. Things have, and still may change daily. ", lat: 37.735380, lng: -119.559996, park: "Yosemite National Park", spot_type: "RV", price_per_night: 35.00, minimum_nights: 1, nearby_attractions: "Yosemite National Park", bring_your_own_tents: false, sites: 9, guests_per_site: 4, park_at_listing: true, ada_access: true, toilet_available: true, pets_allowed: true, campfires: true, picnic_table_available: true, potable_water: true, kitchen: false, showers: false, wifi: false, bins_available: true, laundry: false, electrical_hookup: true, water_hookup: true, generator_allowed: false, sewage_hookup: false, tv_hookup: false, pull_in_site: true, surface_type: "Meadow", max_length: "24ft", surface_levelness: "Mostly flat", slideouts: true, biking: true, hiking: false, boating: false, fishing: false, paddling: false, swimming: false, snow_sports: false, wildlife_watching: false, climbing: false, horseback_riding: false, off_roading: false, mountainous: true, desert: false, forest: true, coastal: false, weather: "Temperate", elevation: "4,000ft+", distance: "Not walking distance", check_in_details: "After 12PM", check_out_details: "Before 11AM", cancellation_policy: "Strict", on_arrival: "Park in booked spot", booking_acceptance: "8 months out")

s1file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/big+sur/camp+1/wilson-ye-A3nkfpJFGJo-unsplash.jpg") 
s1file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/big+sur/camp+1/courtney-corlew-qw8IJEIWoXg-unsplash.jpg") 
s1file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/big+sur/camp+1/sage-friedman-N561DZ3NfVM-unsplash.jpg") 
spot1.spot_photos.attach(io: s1file1, filename: "s1p1.jpg")
spot1.spot_photos.attach(io: s1file2, filename: "s1p2.jpg")
spot1.spot_photos.attach(io: s1file3, filename: "s1p3.jpg")


s2file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/big+sur/glamp+1/blake-wisz-TcgASSD5G04-unsplash.jpg") 
s2file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/big+sur/glamp+1/tobias-tullius-0Bf7UcUYJVU-unsplash.jpg") 
spot2.spot_photos.attach(io: s2file1, filename: "s2p1.jpg")
spot2.spot_photos.attach(io: s2file2, filename: "s2p2.jpg")


s3file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/death+valley/camp+1/tommy-lisbin-6JBhbItRvCA-unsplash.jpg") 
s3file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/death+valley/camp+1/patrick-hendry-pkjYhveQB0Q-unsplash.jpg") 
spot3.spot_photos.attach(io: s3file1, filename: "s3p1.jpg")
spot3.spot_photos.attach(io: s3file2, filename: "s3p1.jpg")


s4file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/death+valley/glamp+1/patrick-schneider-5_f15rvXbK4-unsplash.jpg") 
spot4.spot_photos.attach(io: s4file1, filename: "s4p1.jpg")


s5file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/Joshua+Tree/camp+1/ethan-dow-qMoyLE98Obk-unsplash.jpg") 
s5file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/Joshua+Tree/camp+1/michelle-sharp-JMpNJup-YBY-unsplash.jpg") 
s5file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/Joshua+Tree/camp+1/peter-thomas-crP8WVgw2cQ-unsplash.jpg") 
spot5.spot_photos.attach(io: s5file1, filename: "s5p1.jpg")
spot5.spot_photos.attach(io: s5file2, filename: "s5p2.jpg")
spot5.spot_photos.attach(io: s5file3, filename: "s5p3.jpg")


s6file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/Joshua+Tree/glamp+1/toa-heftiba-fv2jr89ajTE-unsplash.jpg") 
s6file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/Joshua+Tree/glamp+1/dane-deaner-dQF2xtdjh9I-unsplash.jpg") 
s6file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/Joshua+Tree/glamp+1/roberto-nickson-bwIqQ5qQhXs-unsplash.jpg") 
spot6.spot_photos.attach(io: s6file1, filename: "s6p1.jpg")
spot6.spot_photos.attach(io: s6file2, filename: "s6p2.jpg")
spot6.spot_photos.attach(io: s6file3, filename: "s6p3.jpg")


s7file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/Joshua+Tree/glamp+2/garrick-sangil-RrhoLronAf4-unsplash.jpg") 
s7file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/Joshua+Tree/glamp+2/luiz-cent-eyoKIj3WTY4-unsplash.jpg") 
spot7.spot_photos.attach(io: s7file1, filename: "s7p1.jpg")
spot7.spot_photos.attach(io: s7file2, filename: "s7p2.jpg")


s8file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/King'sCanyon/camp1/chris-holder-uY2UIyO5o5c-unsplash.jpg") 
s8file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/King'sCanyon/camp1/scott-goodwill-y8Ngwq34_Ak-unsplash.jpg") 
spot8.spot_photos.attach(io: s8file1, filename: "s8p1.jpg")
spot8.spot_photos.attach(io: s8file2, filename: "s8p2.jpg")


s9file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/King'sCanyon/rv/daniel-j-schwarz-k8tU6lYmuOM-unsplash.jpg") 
s9file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/King'sCanyon/rv/brina-blum-LUfmqLfEAoE-unsplash.jpg") 
s9file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/King'sCanyon/rv/mikel-ibarluzea-45lDCN6lVVA-unsplash.jpg") 
spot9.spot_photos.attach(io: s9file1, filename: "s9p1.jpg")
spot9.spot_photos.attach(io: s9file2, filename: "s9p2.jpg")
spot9.spot_photos.attach(io: s9file3, filename: "s9p3.jpg")


s10file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lassen+volcanic/camp1/ryan-chua-z4VS-7Haodw-unsplash.jpg") 
spot10.spot_photos.attach(io: s10file1, filename: "s10p1.jpg")


s11file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lassen+volcanic/camp2/michael-guite-1o41Wy3Z3kc-unsplash.jpg") 
s11file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lassen+volcanic/camp2/daniel-nainggolan-W6dRiZHDZAo-unsplash.jpg") 
spot11.spot_photos.attach(io: s11file1, filename: "s11p1.jpg")
spot11.spot_photos.attach(io: s11file2, filename: "s11p2.jpg")


s12file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lassen+volcanic/glamp1/gv-chana-Wws-dcCOXh0-unsplash+(1).jpg") 
s12file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lassen+volcanic/glamp1/nick-dunlap-EDYPQOHdKHg-unsplash.jpg") 
spot12.spot_photos.attach(io: s12file1, filename: "s12p1.jpg")
spot12.spot_photos.attach(io: s12file2, filename: "s12p2.jpg")


s13file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lassen+volcanic/rv/tobias-tullius-HxEAZylvr2U-unsplash.jpg") 
spot13.spot_photos.attach(io: s13file1, filename: "s13p1.jpg")


s14file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/tahoe+national+forest/camp/denys-nevozhai-63Znf38gnXk-unsplash.jpg") 
s14file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/tahoe+national+forest/camp/etienne-delorieux-oLbFi_xNi1c-unsplash.jpg") 
s14file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/tahoe+national+forest/camp/timothy-meinberg-xqV9QdGOSas-unsplash.jpg") 
spot14.spot_photos.attach(io: s14file1, filename: "s14p1.jpg")
spot14.spot_photos.attach(io: s14file2, filename: "s14p2.jpg")
spot14.spot_photos.attach(io: s14file3, filename: "s14p3.jpg")


s15file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/tahoe+national+forest/camp2/josh-hild-8f_VQ3EFbTg-unsplash.jpg") 
s15file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/tahoe+national+forest/camp2/andreas-ronningen-i9FLJwYhVQs-unsplash.jpg") 
s15file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/tahoe+national+forest/camp2/brooks-rice-8-jqqr-rpo0-unsplash.jpg")  
spot15.spot_photos.attach(io: s15file1, filename: "s15p1.jpg")
spot15.spot_photos.attach(io: s15file2, filename: "s15p2.jpg")
spot15.spot_photos.attach(io: s15file3, filename: "s15p3.jpg")


s16file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/tahoe+national+forest/glamp/kristin-ellis-qHlUwZLS5F4-unsplash.jpg") 
s16file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/tahoe+national+forest/glamp/andrew-ly-IcnD64M9Xlk-unsplash.jpg") 
s16file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/tahoe+national+forest/glamp/andrea-davis-4nIUQmFu3G0-unsplash.jpg") 
spot16.spot_photos.attach(io: s16file1, filename: "s16p1.jpg")
spot16.spot_photos.attach(io: s16file2, filename: "s16p2.jpg")
spot16.spot_photos.attach(io: s16file3, filename: "s16p3.jpg")


s17file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/tahoe+national+forest/rv/andrew-sterling-HH9Z6VmIOMk-unsplash.jpg") 
spot17.spot_photos.attach(io: s17file1, filename: "s17p1.jpg")


s18file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/tahoe+national+forest/rv2/jeremy-bishop-RvxvbJKad-U-unsplash.jpg") 
spot18.spot_photos.attach(io: s18file1, filename: "s18p1.jpg")


s19file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/yosemite/camp1/tommy-lisbin-2DH-qMX6M4E-unsplash.jpg") 
s19file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/yosemite/camp1/myles-tan-IWCljYv1TJw-unsplash.jpg") 
s19file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/yosemite/camp1/mike-erskine-S_VbdMTsdiA-unsplash.jpg") 
spot19.spot_photos.attach(io: s19file1, filename: "s19p1.jpg")
spot19.spot_photos.attach(io: s19file2, filename: "s19p2.jpg")
spot19.spot_photos.attach(io: s19file3, filename: "s19p3.jpg")


s20file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/yosemite/camp2/richard-cordones-sjzCtWVsx-A-unsplash+(1).jpg")
s20file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/yosemite/camp2/daiga-ellaby-3beArYu-mUo-unsplash.jpg")
s20file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/yosemite/camp2/kelly-sikkema-uuAItepQWMw-unsplash.jpg")
spot20.spot_photos.attach(io: s20file1, filename: "s20p1.jpg")
spot20.spot_photos.attach(io: s20file2, filename: "s20p2.jpg")
spot20.spot_photos.attach(io: s20file3, filename: "s20p3.jpg")


s21file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/yosemite/glamp1/damien-dufour-photographie-6z5FjJMvI8s-unsplash+copy.jpg")
s21file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/yosemite/glamp1/damien-dufour-photographie-6z5FjJMvI8s-unsplash.jpg")
spot21.spot_photos.attach(io: s21file1, filename: "s21p1.jpg")
spot21.spot_photos.attach(io: s21file2, filename: "s21p2.jpg")


s22file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/yosemite/glamp2/andrea-davis-oWAKjj19SFc-unsplash.jpg")
s22file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/yosemite/glamp2/andrea-davis-n3bQJQheSZs-unsplash.jpg")
s22file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/yosemite/glamp2/andrea-davis-1tpRxlujhws-unsplash.jpg")
spot22.spot_photos.attach(io: s22file1, filename: "s22p1.jpg")
spot22.spot_photos.attach(io: s22file2, filename: "s22p2.jpg")
spot22.spot_photos.attach(io: s22file3, filename: "s22p3.jpg")


s23file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/yosemite/rv/izabela-mierzejewski-SWuFxMb8Y8w-unsplash.jpg")
spot23.spot_photos.attach(io: s23file1, filename: "s23p1.jpg")


bsfile1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/connor-mcsheffrey-xy6VtCbXb0o-unsplash.jpg") 
bsfile2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/darpan-dodiya-adE8wOgKpeM-unsplash.jpg") 
bsfile3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ethan-dow-8Oh2Ph54Hwc-unsplash.jpg") 
bsfile4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/joe-pascavage-Ic0q_M542Is-unsplash.jpg") 
bsfile5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kace-rodriguez-pMK84mYVwTA-unsplash.jpg") 
bsfile6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kace-rodriguez-t_OUw49w3tM-unsplash.jpg") 
bsfile7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kal-visuals-7PWb7JbKxJU-unsplash.jpg") 
bsfile8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kal-visuals-vwFdwHbDvww-unsplash.jpg") 
bsfile9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kristopher-roller-KYl05G0eBY0-unsplash.jpg") 
bsfile10 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kyle-glenn-_PuoQvJx7pM-unsplash.jpg") 
bsfile11 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/noah-buscher-PSnkh76C-Z8-unsplash.jpg") 
bsfile12 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/offcut-hTz-V-GfISU-unsplash.jpg") 
bsfile13 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/robson-hatsukami-morgan-w6FHfoGQO5w-unsplash.jpg") 
bsfile14 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/sage-friedman-Y0YZe-fShzk-unsplash.jpg") 

spot1.vibe_photos.attach(io: bsfile1, filename: "bsv1.jpg")
spot1.vibe_photos.attach(io: bsfile2, filename: "bsv2.jpg")
spot1.vibe_photos.attach(io: bsfile3, filename: "bsv3.jpg")
spot1.vibe_photos.attach(io: bsfile4, filename: "bsv4.jpg")
spot1.vibe_photos.attach(io: bsfile5, filename: "bsv5.jpg")
spot1.vibe_photos.attach(io: bsfile6, filename: "bsv6.jpg")
spot1.vibe_photos.attach(io: bsfile7, filename: "bsv7.jpg")
spot1.vibe_photos.attach(io: bsfile8, filename: "bsv8.jpg")
spot1.vibe_photos.attach(io: bsfile9, filename: "bsv9.jpg")
spot1.vibe_photos.attach(io: bsfile10, filename: "bsv10.jpg")
spot1.vibe_photos.attach(io: bsfile11, filename: "bsv11.jpg")
spot1.vibe_photos.attach(io: bsfile12, filename: "bsv12.jpg")
spot1.vibe_photos.attach(io: bsfile13, filename: "bsv13.jpg")
spot1.vibe_photos.attach(io: bsfile14, filename: "bsv14.jpg")

bs1file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/connor-mcsheffrey-xy6VtCbXb0o-unsplash.jpg") 
bs1file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/darpan-dodiya-adE8wOgKpeM-unsplash.jpg") 
bs1file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ethan-dow-8Oh2Ph54Hwc-unsplash.jpg") 
bs1file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/joe-pascavage-Ic0q_M542Is-unsplash.jpg") 
bs1file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kace-rodriguez-pMK84mYVwTA-unsplash.jpg") 
bs1file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kace-rodriguez-t_OUw49w3tM-unsplash.jpg") 
bs1file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kal-visuals-7PWb7JbKxJU-unsplash.jpg") 
bs1file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kal-visuals-vwFdwHbDvww-unsplash.jpg") 
bs1file9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kristopher-roller-KYl05G0eBY0-unsplash.jpg") 
bs1file10 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kyle-glenn-_PuoQvJx7pM-unsplash.jpg") 
bs1file11 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/noah-buscher-PSnkh76C-Z8-unsplash.jpg") 
bs1file12 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/offcut-hTz-V-GfISU-unsplash.jpg") 
bs1file13 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/robson-hatsukami-morgan-w6FHfoGQO5w-unsplash.jpg") 
bs1file14 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/sage-friedman-Y0YZe-fShzk-unsplash.jpg") 


spot2.vibe_photos.attach(io: bs1file1, filename: "a-bsv1.jpg")
spot2.vibe_photos.attach(io: bs1file2, filename: "a-bsv2.jpg")
spot2.vibe_photos.attach(io: bs1file3, filename: "a-bsv3.jpg")
spot2.vibe_photos.attach(io: bs1file4, filename: "a-bsv4.jpg")
spot2.vibe_photos.attach(io: bs1file5, filename: "a-bsv5.jpg")
spot2.vibe_photos.attach(io: bs1file6, filename: "a-bsv6.jpg")
spot2.vibe_photos.attach(io: bs1file7, filename: "a-bsv7.jpg")
spot2.vibe_photos.attach(io: bs1file8, filename: "a-bsv8.jpg")
spot2.vibe_photos.attach(io: bs1file9, filename: "a-bsv9.jpg")
spot2.vibe_photos.attach(io: bs1file10, filename: "a-bsv10.jpg")
spot2.vibe_photos.attach(io: bs1file11, filename: "a-bsv11.jpg")
spot2.vibe_photos.attach(io: bs1file12, filename: "a-bsv12.jpg")
spot2.vibe_photos.attach(io: bs1file13, filename: "a-bsv13.jpg")
spot2.vibe_photos.attach(io: bs1file14, filename: "a-bsv14.jpg")

dvfile1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/vibe/aldric-rivat-33arh6bTpCw-unsplash.jpg") 
dvfile2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/vibe/berenice-melis-KdpjvfgOP3A-unsplash.jpg") 
dvfile3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/vibe/jehyun-sung-6U5AEmQIajg-unsplash.jpg") 
dvfile4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/vibe/joshua-wilking-bgSKRrYFYxc-unsplash.jpg") 
dvfile5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/vibe/shane-o-lMQrYpgOZLc-unsplash.jpg") 
dvfile6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/vibe/tony-ross-eIsHXGUQNgw-unsplash.jpg") 
spot3.vibe_photos.attach(io: dvfile1, filename: "dv1.jpg")
spot3.vibe_photos.attach(io: dvfile2, filename: "dv2.jpg")
spot3.vibe_photos.attach(io: dvfile3, filename: "dv3.jpg")
spot3.vibe_photos.attach(io: dvfile4, filename: "dv4.jpg")
spot3.vibe_photos.attach(io: dvfile5, filename: "dv5.jpg")
spot3.vibe_photos.attach(io: dvfile6, filename: "dv6.jpg")

dv1file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/vibe/aldric-rivat-33arh6bTpCw-unsplash.jpg") 
dv1file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/vibe/berenice-melis-KdpjvfgOP3A-unsplash.jpg") 
dv1file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/vibe/jehyun-sung-6U5AEmQIajg-unsplash.jpg") 
dv1file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/vibe/joshua-wilking-bgSKRrYFYxc-unsplash.jpg") 
dv1file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/vibe/shane-o-lMQrYpgOZLc-unsplash.jpg") 
dv1file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/vibe/tony-ross-eIsHXGUQNgw-unsplash.jpg") 
spot4.vibe_photos.attach(io: dv1file1, filename: "adv1.jpg")
spot4.vibe_photos.attach(io: dv1file2, filename: "adv2.jpg")
spot4.vibe_photos.attach(io: dv1file3, filename: "adv3.jpg")
spot4.vibe_photos.attach(io: dv1file4, filename: "adv4.jpg")
spot4.vibe_photos.attach(io: dv1file5, filename: "adv5.jpg")
spot4.vibe_photos.attach(io: dv1file6, filename: "adv6.jpg")

jtfile1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/austin-kehmeier-_HZKAqQDTXA-unsplash.jpg") 
jtfile2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/clarisse-meyer-lm19CKBlsJM-unsplash.jpg") 
jtfile3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/daniel-gregoire-ifPS5viyKb8-unsplash.jpg") 
jtfile4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/dane-deaner-9jC9Gk7jgWM-unsplash.jpg") 
jtfile5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/darius-bashar-y6sA8SM1XBg-unsplash.jpg") 
jtfile6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/edward-cisneros-zfYid-u8O38-unsplash.jpg") 
jtfile7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/jeremy-bishop-VsJgTN_yPVQ-unsplash.jpg") 
jtfile8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/jeremy-bishop-oiGdSoreMNE-unsplash.jpg") 
jtfile9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/jeremy-bishop-yS0vsQaEO7o-unsplash.jpg") 
jtfile10 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/lauren-macneish-QZAPkKZStOA-unsplash.jpg") 
jtfile11 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/sam-mgrdichian-4Aev9YjxTrU-unsplash.jpg") 
jtfile12 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/svyatoslav-romanov--zwzOjMb9rY-unsplash.jpg") 

spot5.vibe_photos.attach(io: jtfile1, filename: "jtv1.jpg")
spot5.vibe_photos.attach(io: jtfile2, filename: "jtv2.jpg")
spot5.vibe_photos.attach(io: jtfile3, filename: "jtv3.jpg")
spot5.vibe_photos.attach(io: jtfile4, filename: "jtv4.jpg")
spot5.vibe_photos.attach(io: jtfile5, filename: "jtv5.jpg")
spot5.vibe_photos.attach(io: jtfile6, filename: "jtv6.jpg")
spot5.vibe_photos.attach(io: jtfile7, filename: "jtv7.jpg")
spot5.vibe_photos.attach(io: jtfile8, filename: "jtv8.jpg")
spot5.vibe_photos.attach(io: jtfile9, filename: "jtv9.jpg")
spot5.vibe_photos.attach(io: jtfile10, filename: "jtv10.jpg")
spot5.vibe_photos.attach(io: jtfile11, filename: "jtv11.jpg")
spot5.vibe_photos.attach(io: jtfile12, filename: "jtv12.jpg")


jt1file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/austin-kehmeier-_HZKAqQDTXA-unsplash.jpg") 
jt1file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/clarisse-meyer-lm19CKBlsJM-unsplash.jpg") 
jt1file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/daniel-gregoire-ifPS5viyKb8-unsplash.jpg") 
jt1file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/dane-deaner-9jC9Gk7jgWM-unsplash.jpg") 
jt1file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/darius-bashar-y6sA8SM1XBg-unsplash.jpg") 
jt1file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/edward-cisneros-zfYid-u8O38-unsplash.jpg") 
jt1file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/jeremy-bishop-VsJgTN_yPVQ-unsplash.jpg") 
jt1file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/jeremy-bishop-oiGdSoreMNE-unsplash.jpg") 
jt1file9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/jeremy-bishop-yS0vsQaEO7o-unsplash.jpg") 
jt1file10 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/lauren-macneish-QZAPkKZStOA-unsplash.jpg") 
jt1file11 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/sam-mgrdichian-4Aev9YjxTrU-unsplash.jpg") 
jt1file12 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/svyatoslav-romanov--zwzOjMb9rY-unsplash.jpg") 
spot6.vibe_photos.attach(io: jt1file1, filename: "a-jtv1.jpg")
spot6.vibe_photos.attach(io: jt1file2, filename: "a-jtv2.jpg")
spot6.vibe_photos.attach(io: jt1file3, filename: "a-jtv3.jpg")
spot6.vibe_photos.attach(io: jt1file4, filename: "a-jtv4.jpg")
spot6.vibe_photos.attach(io: jt1file5, filename: "a-jtv5.jpg")
spot6.vibe_photos.attach(io: jt1file6, filename: "a-jtv6.jpg")
spot6.vibe_photos.attach(io: jt1file7, filename: "a-jtv7.jpg")
spot6.vibe_photos.attach(io: jt1file8, filename: "a-jtv8.jpg")
spot6.vibe_photos.attach(io: jt1file9, filename: "a-jtv9.jpg")
spot6.vibe_photos.attach(io: jt1file10, filename: "a-jtv10.jpg")
spot6.vibe_photos.attach(io: jt1file11, filename: "a-jtv11.jpg")
spot6.vibe_photos.attach(io: jt1file12, filename: "a-jtv12.jpg")

jt2file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/austin-kehmeier-_HZKAqQDTXA-unsplash.jpg") 
jt2file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/clarisse-meyer-lm19CKBlsJM-unsplash.jpg") 
jt2file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/daniel-gregoire-ifPS5viyKb8-unsplash.jpg") 
jt2file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/dane-deaner-9jC9Gk7jgWM-unsplash.jpg") 
jt2file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/darius-bashar-y6sA8SM1XBg-unsplash.jpg") 
jt2file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/edward-cisneros-zfYid-u8O38-unsplash.jpg") 
jt2file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/jeremy-bishop-VsJgTN_yPVQ-unsplash.jpg") 
jt2file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/jeremy-bishop-oiGdSoreMNE-unsplash.jpg") 
jt2file9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/jeremy-bishop-yS0vsQaEO7o-unsplash.jpg") 
jt2file10 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/lauren-macneish-QZAPkKZStOA-unsplash.jpg") 
jt2file11 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/sam-mgrdichian-4Aev9YjxTrU-unsplash.jpg") 
jt2file12 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/jtvibe/svyatoslav-romanov--zwzOjMb9rY-unsplash.jpg") 
spot7.vibe_photos.attach(io: jt2file1, filename: "b-jtv1.jpg")
spot7.vibe_photos.attach(io: jt2file2, filename: "b-jtv2.jpg")
spot7.vibe_photos.attach(io: jt2file3, filename: "b-jtv3.jpg")
spot7.vibe_photos.attach(io: jt2file4, filename: "b-jtv4.jpg")
spot7.vibe_photos.attach(io: jt2file5, filename: "b-jtv5.jpg")
spot7.vibe_photos.attach(io: jt2file6, filename: "b-jtv6.jpg")
spot7.vibe_photos.attach(io: jt2file7, filename: "b-jtv7.jpg")
spot7.vibe_photos.attach(io: jt2file8, filename: "b-jtv8.jpg")
spot7.vibe_photos.attach(io: jt2file9, filename: "b-jtv9.jpg")
spot7.vibe_photos.attach(io: jt2file10, filename: "b-jtv10.jpg")
spot7.vibe_photos.attach(io: jt2file11, filename: "b-jtv11.jpg")
spot7.vibe_photos.attach(io: jt2file12, filename: "b-jtv12.jpg")

kcfile1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/andi-kernel-ka-s-M3G8-VNOTGI-unsplash.jpg") 
kcfile2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/dominik-lange--yfsRJR59I8-unsplash.jpg") 
kcfile3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/dustin-belt-4lQtICMAIMo-unsplash.jpg") 
kcfile4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/ian-liberry-9wpb4-NoBWQ-unsplash.jpg") 
kcfile5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/james-lee-X0CnaUxMVds-unsplash.jpg") 
kcfile6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/jeremy-gallman-51Z63a59tKs-unsplash.jpg") 
kcfile7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/joe-wilson-UOyzEWx1iEE-unsplash.jpg") 
kcfile8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/matt-artz-nTRDnDdDYk8-unsplash.jpg") 

spot8.vibe_photos.attach(io: kcfile1, filename: "kcv1.jpg")
spot8.vibe_photos.attach(io: kcfile2, filename: "kcv2.jpg")
spot8.vibe_photos.attach(io: kcfile3, filename: "kcv3.jpg")
spot8.vibe_photos.attach(io: kcfile4, filename: "kcv4.jpg")
spot8.vibe_photos.attach(io: kcfile5, filename: "kcv5.jpg")
spot8.vibe_photos.attach(io: kcfile6, filename: "kcv6.jpg")
spot8.vibe_photos.attach(io: kcfile7, filename: "kcv7.jpg")
spot8.vibe_photos.attach(io: kcfile8, filename: "kcv8.jpg")

kc1file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/andi-kernel-ka-s-M3G8-VNOTGI-unsplash.jpg") 
kc1file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/dominik-lange--yfsRJR59I8-unsplash.jpg") 
kc1file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/dustin-belt-4lQtICMAIMo-unsplash.jpg") 
kc1file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/ian-liberry-9wpb4-NoBWQ-unsplash.jpg") 
kc1file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/james-lee-X0CnaUxMVds-unsplash.jpg") 
kc1file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/jeremy-gallman-51Z63a59tKs-unsplash.jpg") 
kc1file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/joe-wilson-UOyzEWx1iEE-unsplash.jpg") 
kc1file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/kcvibe/matt-artz-nTRDnDdDYk8-unsplash.jpg") 

spot9.vibe_photos.attach(io: kc1file1, filename: "a-kcv1.jpg")
spot9.vibe_photos.attach(io: kc1file2, filename: "a-kcv2.jpg")
spot9.vibe_photos.attach(io: kc1file3, filename: "a-kcv3.jpg")
spot9.vibe_photos.attach(io: kc1file4, filename: "a-kcv4.jpg")
spot9.vibe_photos.attach(io: kc1file5, filename: "a-kcv5.jpg")
spot9.vibe_photos.attach(io: kc1file6, filename: "a-kcv6.jpg")
spot9.vibe_photos.attach(io: kc1file7, filename: "a-kcv7.jpg")
spot9.vibe_photos.attach(io: kc1file8, filename: "a-kcv8.jpg")

lvfile1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/deanna-lewis-FNO8oAeEoWY-unsplash.jpg") 
lvfile2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/gracie-emory-N1fu2NruDkw-unsplash.jpg") 
lvfile3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/holly-mandarich-qF39KxkvpOE-unsplash.jpg") 
lvfile4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/joshua-stannard-zGqVUL30hF0-unsplash.jpg") 
lvfile5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/patrick-bosiger-WVl8kbxVWto-unsplash.jpg") 
lvfile6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/patrick-schneider-4uYs8NmDL1c-unsplash.jpg") 
lvfile7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/thomas-fields-aBKzwOL8reQ-unsplash.jpg") 
lvfile8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/yang-liu-zgFWlRVUwvU-unsplash.jpg") 

spot10.vibe_photos.attach(io: lvfile1, filename: "lvv1.jpg")
spot10.vibe_photos.attach(io: lvfile2, filename: "lvv2.jpg")
spot10.vibe_photos.attach(io: lvfile3, filename: "lvv3.jpg")
spot10.vibe_photos.attach(io: lvfile4, filename: "lvv4.jpg")
spot10.vibe_photos.attach(io: lvfile5, filename: "lvv5.jpg")
spot10.vibe_photos.attach(io: lvfile6, filename: "lvv6.jpg")
spot10.vibe_photos.attach(io: lvfile7, filename: "lvv7.jpg")
spot10.vibe_photos.attach(io: lvfile8, filename: "lvv8.jpg")

lv1file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/deanna-lewis-FNO8oAeEoWY-unsplash.jpg") 
lv1file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/gracie-emory-N1fu2NruDkw-unsplash.jpg") 
lv1file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/holly-mandarich-qF39KxkvpOE-unsplash.jpg") 
lv1file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/joshua-stannard-zGqVUL30hF0-unsplash.jpg") 
lv1file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/patrick-bosiger-WVl8kbxVWto-unsplash.jpg") 
lv1file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/patrick-schneider-4uYs8NmDL1c-unsplash.jpg") 
lv1file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/thomas-fields-aBKzwOL8reQ-unsplash.jpg") 
lv1file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/yang-liu-zgFWlRVUwvU-unsplash.jpg")

spot11.vibe_photos.attach(io: lv1file1, filename: "a-lvv1.jpg")
spot11.vibe_photos.attach(io: lv1file2, filename: "a-lvv2.jpg")
spot11.vibe_photos.attach(io: lv1file3, filename: "a-lvv3.jpg")
spot11.vibe_photos.attach(io: lv1file4, filename: "a-lvv4.jpg")
spot11.vibe_photos.attach(io: lv1file5, filename: "a-lvv5.jpg")
spot11.vibe_photos.attach(io: lv1file6, filename: "a-lvv6.jpg")
spot11.vibe_photos.attach(io: lv1file7, filename: "a-lvv7.jpg")
spot11.vibe_photos.attach(io: lv1file8, filename: "a-lvv8.jpg")

lv2file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/deanna-lewis-FNO8oAeEoWY-unsplash.jpg") 
lv2file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/gracie-emory-N1fu2NruDkw-unsplash.jpg") 
lv2file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/holly-mandarich-qF39KxkvpOE-unsplash.jpg") 
lv2file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/joshua-stannard-zGqVUL30hF0-unsplash.jpg") 
lv2file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/patrick-bosiger-WVl8kbxVWto-unsplash.jpg") 
lv2file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/patrick-schneider-4uYs8NmDL1c-unsplash.jpg") 
lv2file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/thomas-fields-aBKzwOL8reQ-unsplash.jpg") 
lv2file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/yang-liu-zgFWlRVUwvU-unsplash.jpg")

spot12.vibe_photos.attach(io: lv2file1, filename: "b-lvv1.jpg")
spot12.vibe_photos.attach(io: lv2file2, filename: "b-lvv2.jpg")
spot12.vibe_photos.attach(io: lv2file3, filename: "b-lvv3.jpg")
spot12.vibe_photos.attach(io: lv2file4, filename: "b-lvv4.jpg")
spot12.vibe_photos.attach(io: lv2file5, filename: "b-lvv5.jpg")
spot12.vibe_photos.attach(io: lv2file6, filename: "b-lvv6.jpg")
spot12.vibe_photos.attach(io: lv2file7, filename: "b-lvv7.jpg")
spot12.vibe_photos.attach(io: lv2file8, filename: "b-lvv8.jpg")

lv3file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/deanna-lewis-FNO8oAeEoWY-unsplash.jpg") 
lv3file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/gracie-emory-N1fu2NruDkw-unsplash.jpg") 
lv3file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/holly-mandarich-qF39KxkvpOE-unsplash.jpg") 
lv3file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/joshua-stannard-zGqVUL30hF0-unsplash.jpg") 
lv3file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/patrick-bosiger-WVl8kbxVWto-unsplash.jpg") 
lv3file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/patrick-schneider-4uYs8NmDL1c-unsplash.jpg") 
lv3file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/thomas-fields-aBKzwOL8reQ-unsplash.jpg") 
lv3file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/lvvibe/yang-liu-zgFWlRVUwvU-unsplash.jpg")

spot13.vibe_photos.attach(io: lv3file1, filename: "c-lvv1.jpg")
spot13.vibe_photos.attach(io: lv3file2, filename: "c-lvv2.jpg")
spot13.vibe_photos.attach(io: lv3file3, filename: "c-lvv3.jpg")
spot13.vibe_photos.attach(io: lv3file4, filename: "c-lvv4.jpg")
spot13.vibe_photos.attach(io: lv3file5, filename: "c-lvv5.jpg")
spot13.vibe_photos.attach(io: lv3file6, filename: "c-lvv6.jpg")
spot13.vibe_photos.attach(io: lv3file7, filename: "c-lvv7.jpg")
spot13.vibe_photos.attach(io: lv3file8, filename: "c-lvv8.jpg")

thfile1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/alec-krum-96gEIyYKdkA-unsplash.jpg") 
thfile2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/alec-krum-h0eJIhOcSrs-unsplash.jpg") 
thfile3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/dylan-taylor-mdw2kgNqBYo-unsplash.jpg") 
thfile4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/emily-hoehenrieder-lWIcU826-pc-unsplash.jpg") 
thfile5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/emily-karakis-fnsG5UGqG-k-unsplash.jpg") 
thfile6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/katie-musial-sqBWrujuhus-unsplash.jpg") 
thfile7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/parker-ulry-qxLl7yfxReM-unsplash.jpg") 
thfile8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/robert-bye-c5IvumengsE-unsplash.jpg") 
thfile9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/ronan-furuta-lGBViCIqtBY-unsplash.jpg") 

spot14.vibe_photos.attach(io: thfile1, filename: "thv1.jpg")
spot14.vibe_photos.attach(io: thfile2, filename: "thv2.jpg")
spot14.vibe_photos.attach(io: thfile3, filename: "thv3.jpg")
spot14.vibe_photos.attach(io: thfile4, filename: "thv4.jpg")
spot14.vibe_photos.attach(io: thfile5, filename: "thv5.jpg")
spot14.vibe_photos.attach(io: thfile6, filename: "thv6.jpg")
spot14.vibe_photos.attach(io: thfile7, filename: "thv7.jpg")
spot14.vibe_photos.attach(io: thfile8, filename: "thv8.jpg")
spot14.vibe_photos.attach(io: thfile9, filename: "thv9.jpg")

th1file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/alec-krum-96gEIyYKdkA-unsplash.jpg") 
th1file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/alec-krum-h0eJIhOcSrs-unsplash.jpg") 
th1file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/dylan-taylor-mdw2kgNqBYo-unsplash.jpg") 
th1file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/emily-hoehenrieder-lWIcU826-pc-unsplash.jpg") 
th1file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/emily-karakis-fnsG5UGqG-k-unsplash.jpg") 
th1file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/katie-musial-sqBWrujuhus-unsplash.jpg") 
th1file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/parker-ulry-qxLl7yfxReM-unsplash.jpg") 
th1file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/robert-bye-c5IvumengsE-unsplash.jpg") 
th1file9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/ronan-furuta-lGBViCIqtBY-unsplash.jpg") 

spot15.vibe_photos.attach(io: th1file1, filename: "a-thv1.jpg")
spot15.vibe_photos.attach(io: th1file2, filename: "a-thv2.jpg")
spot15.vibe_photos.attach(io: th1file3, filename: "a-thv3.jpg")
spot15.vibe_photos.attach(io: th1file4, filename: "a-thv4.jpg")
spot15.vibe_photos.attach(io: th1file5, filename: "a-thv5.jpg")
spot15.vibe_photos.attach(io: th1file6, filename: "a-thv6.jpg")
spot15.vibe_photos.attach(io: th1file7, filename: "a-thv7.jpg")
spot15.vibe_photos.attach(io: th1file8, filename: "a-thv8.jpg")
spot15.vibe_photos.attach(io: th1file9, filename: "a-thv9.jpg")

th2file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/alec-krum-96gEIyYKdkA-unsplash.jpg") 
th2file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/alec-krum-h0eJIhOcSrs-unsplash.jpg") 
th2file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/dylan-taylor-mdw2kgNqBYo-unsplash.jpg") 
th2file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/emily-hoehenrieder-lWIcU826-pc-unsplash.jpg") 
th2file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/emily-karakis-fnsG5UGqG-k-unsplash.jpg") 
th2file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/katie-musial-sqBWrujuhus-unsplash.jpg") 
th2file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/parker-ulry-qxLl7yfxReM-unsplash.jpg") 
th2file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/robert-bye-c5IvumengsE-unsplash.jpg") 
th2file9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/ronan-furuta-lGBViCIqtBY-unsplash.jpg") 

spot16.vibe_photos.attach(io: th2file1, filename: "b-thv1.jpg")
spot16.vibe_photos.attach(io: th2file2, filename: "b-thv2.jpg")
spot16.vibe_photos.attach(io: th2file3, filename: "b-thv3.jpg")
spot16.vibe_photos.attach(io: th2file4, filename: "b-thv4.jpg")
spot16.vibe_photos.attach(io: th2file5, filename: "b-thv5.jpg")
spot16.vibe_photos.attach(io: th2file6, filename: "b-thv6.jpg")
spot16.vibe_photos.attach(io: th2file7, filename: "b-thv7.jpg")
spot16.vibe_photos.attach(io: th2file8, filename: "b-thv8.jpg")
spot16.vibe_photos.attach(io: th2file9, filename: "b-thv9.jpg")

th3file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/alec-krum-96gEIyYKdkA-unsplash.jpg") 
th3file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/alec-krum-h0eJIhOcSrs-unsplash.jpg") 
th3file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/dylan-taylor-mdw2kgNqBYo-unsplash.jpg") 
th3file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/emily-hoehenrieder-lWIcU826-pc-unsplash.jpg") 
th3file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/emily-karakis-fnsG5UGqG-k-unsplash.jpg") 
th3file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/katie-musial-sqBWrujuhus-unsplash.jpg") 
th3file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/parker-ulry-qxLl7yfxReM-unsplash.jpg") 
th3file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/robert-bye-c5IvumengsE-unsplash.jpg") 
th3file9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/ronan-furuta-lGBViCIqtBY-unsplash.jpg") 

spot17.vibe_photos.attach(io: th3file1, filename: "c-thv1.jpg")
spot17.vibe_photos.attach(io: th3file2, filename: "c-thv2.jpg")
spot17.vibe_photos.attach(io: th3file3, filename: "c-thv3.jpg")
spot17.vibe_photos.attach(io: th3file4, filename: "c-thv4.jpg")
spot17.vibe_photos.attach(io: th3file5, filename: "c-thv5.jpg")
spot17.vibe_photos.attach(io: th3file6, filename: "c-thv6.jpg")
spot17.vibe_photos.attach(io: th3file7, filename: "c-thv7.jpg")
spot17.vibe_photos.attach(io: th3file8, filename: "c-thv8.jpg")
spot17.vibe_photos.attach(io: th3file9, filename: "c-thv9.jpg")

th4file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/alec-krum-96gEIyYKdkA-unsplash.jpg") 
th4file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/alec-krum-h0eJIhOcSrs-unsplash.jpg") 
th4file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/dylan-taylor-mdw2kgNqBYo-unsplash.jpg") 
th4file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/emily-hoehenrieder-lWIcU826-pc-unsplash.jpg") 
th4file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/emily-karakis-fnsG5UGqG-k-unsplash.jpg") 
th4file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/katie-musial-sqBWrujuhus-unsplash.jpg") 
th4file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/parker-ulry-qxLl7yfxReM-unsplash.jpg") 
th4file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/robert-bye-c5IvumengsE-unsplash.jpg") 
th4file9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/thvibe/ronan-furuta-lGBViCIqtBY-unsplash.jpg") 

spot18.vibe_photos.attach(io: th4file1, filename: "d-thv1.jpg")
spot18.vibe_photos.attach(io: th4file2, filename: "d-thv2.jpg")
spot18.vibe_photos.attach(io: th4file3, filename: "d-thv3.jpg")
spot18.vibe_photos.attach(io: th4file4, filename: "d-thv4.jpg")
spot18.vibe_photos.attach(io: th4file5, filename: "d-thv5.jpg")
spot18.vibe_photos.attach(io: th4file6, filename: "d-thv6.jpg")
spot18.vibe_photos.attach(io: th4file7, filename: "d-thv7.jpg")
spot18.vibe_photos.attach(io: th4file8, filename: "d-thv8.jpg")
spot18.vibe_photos.attach(io: th4file9, filename: "d-thv9.jpg")

ysfile1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/bobby-stevenson-vv_haD_9Lus-unsplash.jpg") 
ysfile2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/casey-horner-of7YMA9HpAw-unsplash.jpg") 
ysfile3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/christoph-deinet-B29aPs4Lyp4-unsplash.jpg") 
ysfile4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/edryc-james-p-binoya-Kd1s2nthiV4-unsplash.jpg") 
ysfile5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/claude-piche-lO9LgCjqsBs-unsplash.jpg") 
ysfile6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/henry-xu-0XHo26Jb8dk-unsplash.jpg") 
ysfile7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/johannes-andersson-UCd78vfC8vU-unsplash.jpg") 
ysfile8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordan-pulmano-PoAkzayxhYE-unsplash.jpg") 
ysfile9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordan-pulmano-wMXzwdTcSuA-unsplash.jpg") 
ysfile10 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordi-vich-navarro-OiZKawnGExs-unsplash.jpg") 
ysfile11 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/julia-solovey-UImpFReu2cQ-unsplash.jpg") 
ysfile12 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/luo-lei-oN8uyGr_kME-unsplash.jpg") 
ysfile13 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/pablo-fierro-zOXUvQ3Xo3s-unsplash.jpg") 
ysfile14 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/peter-gonzalez-53fNZ2p-94A-unsplash.jpg") 
ysfile15 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/shownen-Kx67nJZivFg-unsplash.jpg") 

spot19.vibe_photos.attach(io: ysfile1, filename: "ysv1.jpg")
spot19.vibe_photos.attach(io: ysfile2, filename: "ysv2.jpg")
spot19.vibe_photos.attach(io: ysfile3, filename: "ysv3.jpg")
spot19.vibe_photos.attach(io: ysfile4, filename: "ysv4.jpg")
spot19.vibe_photos.attach(io: ysfile5, filename: "ysv5.jpg")
spot19.vibe_photos.attach(io: ysfile6, filename: "ysv6.jpg")
spot19.vibe_photos.attach(io: ysfile7, filename: "ysv7.jpg")
spot19.vibe_photos.attach(io: ysfile8, filename: "ysv8.jpg")
spot19.vibe_photos.attach(io: ysfile9, filename: "ysv9.jpg")
spot19.vibe_photos.attach(io: ysfile10, filename: "ysv10.jpg")
spot19.vibe_photos.attach(io: ysfile11, filename: "ysv11.jpg")
spot19.vibe_photos.attach(io: ysfile12, filename: "ysv12.jpg")
spot19.vibe_photos.attach(io: ysfile13, filename: "ysv13.jpg")
spot19.vibe_photos.attach(io: ysfile14, filename: "ysv14.jpg")
spot19.vibe_photos.attach(io: ysfile15, filename: "ysv15.jpg")

ys1file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/bobby-stevenson-vv_haD_9Lus-unsplash.jpg") 
ys1file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/casey-horner-of7YMA9HpAw-unsplash.jpg") 
ys1file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/christoph-deinet-B29aPs4Lyp4-unsplash.jpg") 
ys1file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/edryc-james-p-binoya-Kd1s2nthiV4-unsplash.jpg") 
ys1file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/claude-piche-lO9LgCjqsBs-unsplash.jpg") 
ys1file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/henry-xu-0XHo26Jb8dk-unsplash.jpg") 
ys1file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/johannes-andersson-UCd78vfC8vU-unsplash.jpg") 
ys1file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordan-pulmano-PoAkzayxhYE-unsplash.jpg") 
ys1file9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordan-pulmano-wMXzwdTcSuA-unsplash.jpg") 
ys1file10 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordi-vich-navarro-OiZKawnGExs-unsplash.jpg") 
ys1file11 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/julia-solovey-UImpFReu2cQ-unsplash.jpg") 
ys1file12 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/luo-lei-oN8uyGr_kME-unsplash.jpg") 
ys1file13 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/pablo-fierro-zOXUvQ3Xo3s-unsplash.jpg") 
ys1file14 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/peter-gonzalez-53fNZ2p-94A-unsplash.jpg") 
ys1file15 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/shownen-Kx67nJZivFg-unsplash.jpg") 


spot20.vibe_photos.attach(io: ys1file1, filename: "a-ysv1.jpg")
spot20.vibe_photos.attach(io: ys1file2, filename: "a-ysv2.jpg")
spot20.vibe_photos.attach(io: ys1file3, filename: "a-ysv3.jpg")
spot20.vibe_photos.attach(io: ys1file4, filename: "a-ysv4.jpg")
spot20.vibe_photos.attach(io: ys1file5, filename: "a-ysv5.jpg")
spot20.vibe_photos.attach(io: ys1file6, filename: "a-ysv6.jpg")
spot20.vibe_photos.attach(io: ys1file7, filename: "a-ysv7.jpg")
spot20.vibe_photos.attach(io: ys1file8, filename: "a-ysv8.jpg")
spot20.vibe_photos.attach(io: ys1file9, filename: "a-ysv9.jpg")
spot20.vibe_photos.attach(io: ys1file10, filename: "a-ysv10.jpg")
spot20.vibe_photos.attach(io: ys1file11, filename: "a-ysv11.jpg")
spot20.vibe_photos.attach(io: ys1file12, filename: "a-ysv12.jpg")
spot20.vibe_photos.attach(io: ys1file13, filename: "a-ysv13.jpg")
spot20.vibe_photos.attach(io: ys1file14, filename: "a-ysv14.jpg")
spot20.vibe_photos.attach(io: ys1file15, filename: "a-ysv15.jpg")

ys2file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/bobby-stevenson-vv_haD_9Lus-unsplash.jpg") 
ys2file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/casey-horner-of7YMA9HpAw-unsplash.jpg") 
ys2file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/christoph-deinet-B29aPs4Lyp4-unsplash.jpg") 
ys2file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/edryc-james-p-binoya-Kd1s2nthiV4-unsplash.jpg") 
ys2file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/claude-piche-lO9LgCjqsBs-unsplash.jpg") 
ys2file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/henry-xu-0XHo26Jb8dk-unsplash.jpg") 
ys2file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/johannes-andersson-UCd78vfC8vU-unsplash.jpg") 
ys2file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordan-pulmano-PoAkzayxhYE-unsplash.jpg") 
ys2file9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordan-pulmano-wMXzwdTcSuA-unsplash.jpg") 
ys2file10 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordi-vich-navarro-OiZKawnGExs-unsplash.jpg") 
ys2file11 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/julia-solovey-UImpFReu2cQ-unsplash.jpg") 
ys2file12 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/luo-lei-oN8uyGr_kME-unsplash.jpg") 
ys2file13 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/pablo-fierro-zOXUvQ3Xo3s-unsplash.jpg") 
ys2file14 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/peter-gonzalez-53fNZ2p-94A-unsplash.jpg") 
ys2file15 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/shownen-Kx67nJZivFg-unsplash.jpg") 


spot21.vibe_photos.attach(io: ys2file1, filename: "b-ysv1.jpg")
spot21.vibe_photos.attach(io: ys2file2, filename: "b-ysv2.jpg")
spot21.vibe_photos.attach(io: ys2file3, filename: "b-ysv3.jpg")
spot21.vibe_photos.attach(io: ys2file4, filename: "b-ysv4.jpg")
spot21.vibe_photos.attach(io: ys2file5, filename: "b-ysv5.jpg")
spot21.vibe_photos.attach(io: ys2file6, filename: "b-ysv6.jpg")
spot21.vibe_photos.attach(io: ys2file7, filename: "b-ysv7.jpg")
spot21.vibe_photos.attach(io: ys2file8, filename: "b-ysv8.jpg")
spot21.vibe_photos.attach(io: ys2file9, filename: "b-ysv9.jpg")
spot21.vibe_photos.attach(io: ys2file10, filename: "b-ysv10.jpg")
spot21.vibe_photos.attach(io: ys2file11, filename: "b-ysv11.jpg")
spot21.vibe_photos.attach(io: ys2file12, filename: "b-ysv12.jpg")
spot21.vibe_photos.attach(io: ys2file13, filename: "b-ysv13.jpg")
spot21.vibe_photos.attach(io: ys2file14, filename: "b-ysv14.jpg")
spot21.vibe_photos.attach(io: ys2file15, filename: "b-ysv15.jpg")

ys3file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/bobby-stevenson-vv_haD_9Lus-unsplash.jpg") 
ys3file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/casey-horner-of7YMA9HpAw-unsplash.jpg") 
ys3file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/christoph-deinet-B29aPs4Lyp4-unsplash.jpg") 
ys3file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/edryc-james-p-binoya-Kd1s2nthiV4-unsplash.jpg") 
ys3file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/claude-piche-lO9LgCjqsBs-unsplash.jpg") 
ys3file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/henry-xu-0XHo26Jb8dk-unsplash.jpg") 
ys3file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/johannes-andersson-UCd78vfC8vU-unsplash.jpg") 
ys3file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordan-pulmano-PoAkzayxhYE-unsplash.jpg") 
ys3file9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordan-pulmano-wMXzwdTcSuA-unsplash.jpg") 
ys3file10 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordi-vich-navarro-OiZKawnGExs-unsplash.jpg") 
ys3file11 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/julia-solovey-UImpFReu2cQ-unsplash.jpg") 
ys3file12 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/luo-lei-oN8uyGr_kME-unsplash.jpg") 
ys3file13 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/pablo-fierro-zOXUvQ3Xo3s-unsplash.jpg") 
ys3file14 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/peter-gonzalez-53fNZ2p-94A-unsplash.jpg") 
ys3file15 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/shownen-Kx67nJZivFg-unsplash.jpg") 


spot22.vibe_photos.attach(io: ys3file1, filename: "c-ysv1.jpg")
spot22.vibe_photos.attach(io: ys3file2, filename: "c-ysv2.jpg")
spot22.vibe_photos.attach(io: ys3file3, filename: "c-ysv3.jpg")
spot22.vibe_photos.attach(io: ys3file4, filename: "c-ysv4.jpg")
spot22.vibe_photos.attach(io: ys3file5, filename: "c-ysv5.jpg")
spot22.vibe_photos.attach(io: ys3file6, filename: "c-ysv6.jpg")
spot22.vibe_photos.attach(io: ys3file7, filename: "c-ysv7.jpg")
spot22.vibe_photos.attach(io: ys3file8, filename: "c-ysv8.jpg")
spot22.vibe_photos.attach(io: ys3file9, filename: "c-ysv9.jpg")
spot22.vibe_photos.attach(io: ys3file10, filename: "c-ysv10.jpg")
spot22.vibe_photos.attach(io: ys3file11, filename: "c-ysv11.jpg")
spot22.vibe_photos.attach(io: ys3file12, filename: "c-ysv12.jpg")
spot22.vibe_photos.attach(io: ys3file13, filename: "c-ysv13.jpg")
spot22.vibe_photos.attach(io: ys3file14, filename: "c-ysv14.jpg")
spot22.vibe_photos.attach(io: ys3file15, filename: "c-ysv15.jpg")

ys4file1 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/bobby-stevenson-vv_haD_9Lus-unsplash.jpg") 
ys4file2 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/casey-horner-of7YMA9HpAw-unsplash.jpg") 
ys4file3 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/christoph-deinet-B29aPs4Lyp4-unsplash.jpg") 
ys4file4 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/edryc-james-p-binoya-Kd1s2nthiV4-unsplash.jpg") 
ys4file5 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/claude-piche-lO9LgCjqsBs-unsplash.jpg") 
ys4file6 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/henry-xu-0XHo26Jb8dk-unsplash.jpg") 
ys4file7 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/johannes-andersson-UCd78vfC8vU-unsplash.jpg") 
ys4file8 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordan-pulmano-PoAkzayxhYE-unsplash.jpg") 
ys4file9 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordan-pulmano-wMXzwdTcSuA-unsplash.jpg") 
ys4file10 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/jordi-vich-navarro-OiZKawnGExs-unsplash.jpg") 
ys4file11 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/julia-solovey-UImpFReu2cQ-unsplash.jpg") 
ys4file12 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/luo-lei-oN8uyGr_kME-unsplash.jpg") 
ys4file13 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/pablo-fierro-zOXUvQ3Xo3s-unsplash.jpg") 
ys4file14 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/peter-gonzalez-53fNZ2p-94A-unsplash.jpg") 
ys4file15 = open("https://calcamper-seed.s3-us-west-1.amazonaws.com/ynvibe/shownen-Kx67nJZivFg-unsplash.jpg") 


spot23.vibe_photos.attach(io: ys4file1, filename: "d-ysv1.jpg")
spot23.vibe_photos.attach(io: ys4file2, filename: "d-ysv2.jpg")
spot23.vibe_photos.attach(io: ys4file3, filename: "d-ysv3.jpg")
spot23.vibe_photos.attach(io: ys4file4, filename: "d-ysv4.jpg")
spot23.vibe_photos.attach(io: ys4file5, filename: "d-ysv5.jpg")
spot23.vibe_photos.attach(io: ys4file6, filename: "d-ysv6.jpg")
spot23.vibe_photos.attach(io: ys4file7, filename: "d-ysv7.jpg")
spot23.vibe_photos.attach(io: ys4file8, filename: "d-ysv8.jpg")
spot23.vibe_photos.attach(io: ys4file9, filename: "d-ysv9.jpg")
spot23.vibe_photos.attach(io: ys4file10, filename: "d-ysv10.jpg")
spot23.vibe_photos.attach(io: ys4file11, filename: "d-ysv11.jpg")
spot23.vibe_photos.attach(io: ys4file12, filename: "d-ysv12.jpg")
spot23.vibe_photos.attach(io: ys4file13, filename: "d-ysv13.jpg")
spot23.vibe_photos.attach(io: ys4file14, filename: "d-ysv14.jpg")
spot23.vibe_photos.attach(io: ys4file15, filename: "d-ysv15.jpg")

